import { useState } from "react";

function GoalModal({ goal, onClose, onSave }) {
  const [form, setForm] = useState({ name: goal?.name ?? "", target: goal?.target?.toString() ?? "", current: goal?.current?.toString() ?? "", targetDate: goal?.targetDate ?? "" });
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = (event) => { event.preventDefault(); onSave({ ...goal, ...form, target: Number(form.target), current: Number(form.current) }); };
  const editing = Boolean(goal);
  return <div className="modal-backdrop" role="presentation"><section className="transaction-modal goal-modal" role="dialog" aria-modal="true" aria-labelledby="goal-modal-title"><div className="modal-header"><div><p className="modal-kicker">{editing ? "UPDATE GOAL" : "NEW GOAL"}</p><h2 id="goal-modal-title">{editing ? "Edit goal" : "Create a goal"}</h2></div><button className="modal-close" type="button" onClick={onClose} aria-label="Close modal">×</button></div><form onSubmit={submit}><div className="form-grid goal-form"><label className="form-field form-field--wide"><span>Goal name</span><input name="name" value={form.name} onChange={update} placeholder="e.g. Emergency fund" required /></label><label className="form-field"><span>Target amount</span><div className="amount-input"><span>₹</span><input type="number" min="1" step="1" name="target" value={form.target} onChange={update} placeholder="0" required /></div></label><label className="form-field"><span>Current saved amount</span><div className="amount-input"><span>₹</span><input type="number" min="0" step="1" name="current" value={form.current} onChange={update} placeholder="0" required /></div></label><label className="form-field form-field--wide"><span>Target date</span><input type="date" name="targetDate" value={form.targetDate} onChange={update} required /></label></div><div className="modal-actions"><button type="button" className="button button--secondary" onClick={onClose}>Cancel</button><button type="submit" className="button button--primary">{editing ? "Save changes" : "Create goal"}</button></div></form></section></div>;
}
export default GoalModal;
